name: steps examples

on:
  push

jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Codepush
        uses: NishanthShankar/codepush-action@master
        with:
          args: release-react -d Production
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
      - name: verification of node version
        run: node --version
